name: snipeit

on:
  push:
    branches: [ selfhosted-runners ]
  
jobs:

  build:
    name: CI/CD-snipeit
    runs-on: self-hosted
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@master
      with:
        host: 52.210.242.71
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          whoami
          cd /srv/
          ls -lrt
